apiVersion: apps/v1
kind: Deployment
metadata:
  name: nginx-green
  labels:
    app: nginx
    deploy: green
spec:
  replicas: 2
  selector:
    matchLabels:
      app: nginx
      deploy: green
  template:
    metadata:
      labels:
        app: nginx
        deploy: green
    spec:
      containers:
      - name: nginx
        image: httpd
        ports:
        - containerPort: 80
