apiVersion: apps/v1
kind: Deployment
metadata:
  name: nginx-blue
  labels:
    app: nginx
    deploy: blue
spec:
  replicas: 2
  selector:
    matchLabels:
      app: nginx
      deploy: blue
  template:
    metadata:
      labels:
        app: nginx
        deploy: blue
    spec:
      containers:
      - name: nginx
        image: nginx:1.14.2
        ports:
        - containerPort: 80
